name: Continuous integration workflow.
run-name: ${{ github.event_name }} by ${{ github.actor }} on branch ${{ github.ref }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create virtual environment and install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest